# Generated by Django 5.0.1 on 2024-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(max_length=1000),
        ),
    ]
